apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: {{ .Release.Name }}-cloudfront-authpolicy
  namespace: {{ .Values.namespace }}
spec:
  rules:
  - from:
    - source:
        remoteIpBlocks: []
