apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-update-script
  namespace: {{ .Values.namespace }}
data:
  update-cloudfront-ips.sh: |
    #!/bin/sh
    apt-get update && apt-get install -y jq curl
    cloudfront_ips=$(curl -s {{ .Values.cloudfrontIpUrl }} | jq -r '.CLOUDFRONT_GLOBAL_IP_LIST | map("- " + .) | join("\n")')
    cat <<EOF | kubectl apply -f -
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: {{ .Release.Name }}-cloudfront-authpolicy
  namespace: {{ .Values.namespace }}
spec:
  rules:
  - from:
    - source:
        ipBlocks:
$cloudfront_ips
EOF
