apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-update-cloudfront-ips
  namespace: {{ .Values.namespace }}
spec:
  schedule: "{{ .Values.cronSchedule }}"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: {{ .Release.Name }}-sa
          containers:
            - name: update-cloudfront-ips
              image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
              command: ["/bin/sh", "/scripts/update-cloudfront-ips.sh"]
              volumeMounts:
                - name: script-volume
                  mountPath: /scripts
                  readOnly: true
          restartPolicy: OnFailure
          volumes:
            - name: script-volume
              configMap:
                name: {{ .Release.Name }}-update-script
                defaultMode: 0755
