apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-update-cloudfront-ips
  namespace: {{ .Values.namespace }}
spec:
  schedule: "{{ .Values.cronSchedule }}"  # Runs every day at midnight
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: update-cloudfront-ips
              image: dtzar/helm-kubectl:latest
              command: ["/bin/sh", "-c", "chmod +x /scripts/update-cloudfront-ips.sh && /scripts/update-cloudfront-ips.sh"]
              volumeMounts:
                - name: script-volume
                  mountPath: /scripts
                  readOnly: true
          restartPolicy: OnFailure
          volumes:
            - name: script-volume
              configMap:
                name: {{ .Release.Name }}-update-script
      restartPolicy: OnFailure
